### ISSUE TITLE
mocking raw body submits

### ISSUE THREAD

**Issue by bingomanatee** [mjackson/stratajs.org#1]
I am trying to mock a REST style POST 

   new_item = {id:1, name:'dava'};

```
    var content = JSON.stringify(new_item);
    var contentLength = Buffer.byteLength(content).toString(10);
    var serverName = "example.org";
    var env_data = {protocol:"http:",
        protocolVersion:"1.1",
        requestMethod:"POST",
        requestTime:new Date,
        remoteAddr:"127.0.0.1",
        serverName:serverName,
        serverPort:"443",
        pathInfo:"/rest_path/1",
        userAgent:"test suite",
        headers:{
            "Host":serverName,
            "User-Agent":this.userAgent,
            "Content-Length":this.contentLength
        },
        input:new BufferedStream(content)
    };
```

the result is that the entire expression gets set as a POST parameter:

when echoing env, I get:
{ ...
  strataBody: { '{"id":1,"name":"dava"}': '' },
}

How can you create/mock raw body POSTs in strata?

Dave

**Comment by mjackson** [comment]
If you're trying to get the JSON blob to parse properly on the server side, you need to set the Content-Type request header to "application/json". Otherwise, your approach is correct.

BTW, for issues like these I'd prefer it if you sent an email to the [strata mailing list](http://groups.google.com/group/stratajs) or just sent me an email directly. Thanks!

**Comment by bingomanatee** [comment]
Thanks -- I've got fairly far with a rest engine based on strata. I really like the state + callback system.
